Update compile
adjusted to grab latest meteor

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,13 +1,14 @@
 #!/bin/sh
 
+echo "ARGS to: $0 $*"
 BUILD_DIR=$1
 CACHE_DIR=$2
+
+echo "`ls -l $BUILD_DIR`"
+
 METEOR_HOME=$BUILD_DIR/.meteor/local
 PATH=$METEOR_HOME/usr/bin:$METEOR_HOME/usr/lib/meteor/bin:$PATH
 
-# Unfortunately heroku buildpacks don't let you pass parameters
-# to this script, so if you want to change the version of meteor,
-# you'll have to fork and hard-code this.
 METEOR_VERSION=blaze-rc0
 
 fetch_meteor() {
@@ -16,25 +17,39 @@ fetch_meteor() {
     return
   fi
 
-
+  eval $(curl install.meteor.com | grep '^VERSION=')
   PACKAGE=meteor_${METEOR_VERSION}-1_amd64.deb
 
-  echo "Fetching meteor deb package"
-  curl -o "$CACHE_DIR/$PACKAGE" "http://d3sqy0vbqsdhku.cloudfront.net/${PACKAGE}"
+#  echo "Fetching meteor deb package"
+#  curl -o "$CACHE_DIR/$PACKAGE" "http://d3sqy0vbqsdhku.cloudfront.net/${PACKAGE}"
+#  echo "`ls -l $CACHE_DIR/$PACKAGE`"
+  echo 'Installing Meteor'
+  echo "`curl https://install.meteor.com/ | sh 2>&1`" || echo FAIL
 
-  echo "Unpacking meteor"
-  [ ! -d "$METEOR_HOME" ] && mkdir -p "$METEOR_HOME"
-  ar p "$CACHE_DIR/$PACKAGE" data.tar.gz | tar -C "$METEOR_HOME" -zxf -
+#  echo "Unpacking meteor to $METEOR_HOME from $CACHE_DIR/$PACKAGE"
+#  [ ! -d "$METEOR_HOME" ] && mkdir -p "$METEOR_HOME"
+#  ar -p "$CACHE_DIR/$PACKAGE" data.tar.gz | tar -C "$METEOR_HOME" -zxf -
 }
 
 build() {
   ( 
     cd $BUILD_DIR
+    echo "Creating scrach meteor app in `pwd`/scratch_app"
+    echo "`${HOME}/.meteor/tools/latest/launch-meteor create scratch_app`" || echo FAIL
+echo "`find ./scratch_app/ -type f`"
+    echo "Copying .meteor into our app"
+    mv scratch_app/.meteor . #; rm -rf scratch_app
+echo "`find . -type f`"
     echo "Building meteor bundle"
-    meteor bundle $CACHE_DIR/bundle.tar.gz 
+    echo "`${HOME}/.meteor/tools/latest/launch-meteor bundle $CACHE_DIR/bundle.tar.gz 2>&1`" || echo FAIL
+echo "`ls -l $CACHE_DIR`"
+    echo "Making Meteor/local/build"
     mkdir -p $BUILD_DIR/.meteor/local/build
-    tar -zxf $CACHE_DIR/bundle.tar.gz --strip-components 1 -C $BUILD_DIR/.meteor/local/build
+    echo "unzipping app bundle"
+    tar -zxf $CACHE_DIR/bundle.tar.gz --strip-components 1 -C $BUILD_DIR/.meteor/local/build || echo FAIL
+    echo "removing bundle archive"
     rm $CACHE_DIR/bundle.tar.gz
+    echo "build-pack done"
   )
 }
 
@@ -44,9 +59,5 @@ build() {
 fetch_meteor
 build
 
-echo "Checking for post_compile script"
-if [ -f $BUILD_DIR/bin/post_compile ] ; then
-    echo "-----> Running post_compile hook"
-    chmod +x $BUILD_DIR/bin/post_compile
-    $BUILD_DIR/bin/post_compile
-fi
+echo "in meteor: $METEOR_HOME"
+echo "`find $METEOR_HOME -type f -name node`"
